version: '3'
services:
  jupyter:
    build: 
      context: ./jupyter-lab
    ports:
    - "8888:8888"
    environment:
      JUPYTE_ENABLE_LAB: 'yes'
    volumes:
      - ./projects:/home/projects
  tf-server:
    image: tensorflow/serving
    ports:
    - "8501:8501"
    environment:
      MODEL_NAME: 'mnist'
    volumes:
      - ./models/mnist:/models/mnist